name: "Hello World Action"
description: "Says hello to a user provided as input"
inputs:
  who-to-greet:
    description: "who to greet"
    required: true
    default: "world"
outputs: 
  time:
    description: "The time when we said hello"

runs:
  using: "docker"
  image: "./.github/hello-world-docker-action/Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
